train_data = [
    ("List out Doctor Aisha's Appointments", "db"),
    ("What doctor's are Available now", "db"),
    ("I want to login", "Auth"),
    ("Can I get to see my Profile", "Auth_Profile"),
    ("Please sign me up", "Auth"),
    ("I would like to create an account", "Auth"),
    ("I would like to change my email", "Auth_Profile"),
    ("Can you log me out?", "Auth_logout"),
    ("Can I change the passcode", "Auth_Profile"),
    ("I want to add another email to my account", "Auth_Profile"),
    ("How many doctors does this hospital have?", "RAG"),
    ("When was this hospital established?", "RAG"),
    ("Patients waiting for Orthopedic consultation", "db"),
    ("Timing of Optician", "RAG"),
    ("What are the hospital timings?", "RAG"),
    ("Show me my profile", "RAG"),
    ("What are diabetes?", "LLM"),
    ("Why is CPR done?", "LLM"),
    ("What is the study of the heart called?", "LLM"),
    ("Who is the head of Cardiology?", "RAG"),
    ("Can I update my contact number?", "Auth_Profile"),
    ("What services are available at this hospital?", "RAG"),
    ("Are there any Pediatricians on duty now?", "db"),
    ("Where is the nearest pharmacy?", "RAG"),
    ("I forgot my password", "Auth"),
    ("Can I delete my account?", "Auth_Profile"),
    ("Please sign me out of all devices", "Auth_logout"),
    ("How many appointments are scheduled today?", "db"),
    ("Can I reschedule my appointment?", "db"),
    ("What are the visiting hours?", "RAG"),
    ("What is an MRI scan?", "LLM"),
    ("Can you tell me about flu symptoms?", "LLM"),
    ("Where can I park?", "RAG"),
    ("What should I do for chest pain?", "LLM"),
    ("Show me all appointments with Dr. Smith", "db"),
    ("Who are the on-call doctors for today?", "db"),
    ("What are the reviews of this hospital?", "RAG"),
    ("How do I reset my password?", "Auth"),
    ("Is there a children’s ward?", "RAG"),
    ("Who can I contact for billing issues?", "RAG"),
]
