train_data = [
    ("List out Doctor Aisha's Appointments", "db"),
    ("What doctor's are Available now", "db"),
    ("I want to login", "Auth"),
    ("Can I get to see my Profile", "Auth_Profile"),
    ("Please sign me up", "Auth"),
    ("I would like to create an account", "Auth"),
    ("I would like to change my email", "Auth_Profile"),
    ("Can you log me out?", "Auth_logout"),
    ("Can I change the passcode", "Auth_Profile"),
    ("I want to add another email to my account", "Auth_Profile"),
    ("How many doctors does this hospital have?", "RAG"),
    ("When was this hospital established?", "RAG"),
    ("Patients waiting for Orthopedic consultation", "db"),
    ("Timing of Optician", "RAG"),
    ("What are the hospital timings?", "RAG"),
    ("Show me my profile", "RAG"),
    ("What are diabetes?", "LLM"),
    ("Why is CPR done?", "LLM"),
    ("What is the study of the heart called?", "LLM"),
    ("Who is the head of Cardiology?", "RAG"),
    ("Can I update my contact number?", "Auth_Profile"),
    ("What services are available at this hospital?", "RAG"),
    ("Are there any Pediatricians on duty now?", "db"),
    ("Where is the nearest pharmacy?", "RAG"),
    ("I forgot my password", "Auth"),
    ("Can I delete my account?", "Auth_Profile"),
    ("Please sign me out of all devices", "Auth_logout"),
    ("How many appointments are scheduled today?", "db"),
    ("Can I reschedule my appointment?", "db"),
    ("What are the visiting hours?", "RAG"),
    ("What is an MRI scan?", "LLM"),
    ("Can you tell me about flu symptoms?", "LLM"),
    ("Where can I park?", "RAG"),
    ("What should I do for chest pain?", "LLM"),
    ("Show me all appointments with Dr. Smith", "db"),
    ("Who are the on-call doctors for today?", "db"),
    ("What are the reviews of this hospital?", "RAG"),
    ("How do I reset my password?", "Auth"),
    ("Is there a children’s ward?", "RAG"),
    ("Who can I contact for billing issues?", "RAG"),
    ("What are the Timings of Dr. Batra?", "RAG"),
    ("List today's appointments with Dr. Ray", "db"),
    ("What services does the Neurology department offer?", "RAG"),
    ("Show my recent activity log", "Auth_Profile"),
    ("Is Dr. Sarah available this evening?", "db"),
    ("Can I update my address?", "Auth_Profile"),
    ("How can I schedule a new appointment?", "db"),
    ("I want to view my medical history", "db"),
    ("Please log out of this device", "Auth_logout"),
    ("Who are the available cardiologists?", "db"),
    ("Can you register me as a new patient?", "Auth"),
    ("I would like to book a follow-up with Dr. Kim", "db"),
    ("Can I update my profile picture?", "Auth_Profile"),
    ("Are there any doctors specializing in dermatology?", "db"),
    ("Show the current waiting list for Dr. Ahmed", "db"),
    ("What treatments are offered for arthritis?", "LLM"),
    ("Explain the process of a CT scan", "LLM"),
    ("List all the doctors in Pediatrics", "RAG"),
    ("How can I delete my account permanently?", "Auth_Profile"),
    ("Tell me the hospital’s emergency contact number", "RAG"),
    ("Can I access my medical records?", "db"),
    ("What are the latest visiting hours?", "RAG"),
    ("When does the pharmacy close?", "RAG"),
    ("How do I log out of all sessions?", "Auth_logout"),
    ("Are there any doctors on duty in the Oncology department?", "db"),
    ("Tell me about symptoms of high blood pressure", "LLM"),
    ("How can I create a family account?", "Auth"),
    ("I want to modify my appointment details", "db"),
    ("Can I change my password?", "Auth"),
    ("Who is on the Board of Directors?", "RAG"),
    ("List all appointments for this week", "db"),
    ("What do I do if I have a fever?", "LLM"),
    ("Show doctors with morning shifts", "db"),
    ("Can I sign out of other devices?", "Auth_logout"),
    ("Are there doctors specializing in respiratory care?", "RAG"),
    ("Who can I reach out to for surgery inquiries?", "RAG"),
    ("What are symptoms of anxiety?", "LLM"),
    ("How do I sign up?", "Auth"),
    ("I need to reset my security question", "Auth_Profile"),
    ("List all departments in this hospital", "RAG"),
    ("Show available slots with Dr. Patel", "db"),
    ("What should I bring to my appointment?", "LLM"),
    ("Can I add a secondary phone number?", "Auth_Profile"),
    ("I want to view my prescription history", "db"),
    ("How many specialists are on staff?", "RAG"),
    ("What is a typical recovery time for knee surgery?", "LLM"),
    ("Where is the cardiology department located?", "RAG"),
    ("Who heads the oncology department?", "RAG"),
    ("What should I do if I lose my medical card?", "RAG"),
    ("I need help changing my username", "Auth_Profile"),
    ("Are there any on-call doctors now?", "db"),
    ("Tell me about diabetes management", "LLM"),
]
